title: Kristin Chang # your name (or website title) here

logo: "images/LApic10.jpg" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/KristinChang_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kristin-chang-upenn2022/">LinkedIn</a> |
  <a href="https://github.com/kristinchang">GitHub</a>
  </p>
   
  <p align="justify">
  Dual Masters of City Planning and Urban Spatial Analytics at UPenn, Expected Graduation: December 2022
  <br><br>
  Hi! I'm a graduate student at the University of Pennsylvania interested in exploring creative ways to leverage public sector data. Passionate about creating equitable solutions 
  to address climate change, food insecurity, and health and transportation accessibility gaps.
  <br><br>
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
